### ISSUE TITLE
wcsadmin help 

### ISSUE THREAD

**Issue by herlak** [ThaPwned/WCS-Contents#2]
[SP] Une erreur s'est produite:
Traceback (most recent call last):
  File "../addons/source-python/packages/source-python/commands/auth.py", line 44, in __call__
    return self.callback(*args)
  File "../addons/source-python/packages/source-python/menus/queue.py", line 267, in _menuselect_callback
    _radio_queues[index]._select(choice)
  File "../addons/source-python/packages/source-python/menus/queue.py", line 126, in _select
    next_menu = active_menu._select(self._index, choice)
  File "../addons/source-python/packages/source-python/menus/radio.py", line 316, in _select
    return super()._select(player_index, choice_index)
  File "../addons/source-python/packages/source-python/menus/radio.py", line 113, in _select
    self._player_pages[player_index].options[choice_index])
  File "../addons/source-python/packages/source-python/menus/base.py", line 122, in _select
    return self.select_callback(self, player_index, choice_index)
  File "../addons/source-python/plugins/wcs/core/menus/select.py", line 571, in wcsadmin_management_races_add_menu_select
    data['races'].append(option.value)

KeyError: 'races'

I got rid of the error by deleting a file items.json  cfg/source-python/wcs/...
races/items/ working in the game
is this normal’’?
But the error remains [SP] Avertissement rencontré:
  File '../addons/source-python/plugins/wcs/core/modules/races/manager.py', line 199: UserWarning
    Unable to find the default race "". Using "undead_scourge" as temporary default
        race.

**Comment by herlak** [comment]
https://www.up-00.com/pf2uooi1bmh7

**Comment by herlak** [comment]
Is this normal I liked so much the last change just lacks help
https://www.up-00.com/7mdm2maznwlj
I'm sorry that was a translation error (Google traduction) 
Please help I guess the shaper in a file cfg/source-python/wcs/*.json

**Comment by ThaPwned** [comment]
> [SP] Une erreur s'est produite:
Traceback (most recent call last):
File "../addons/source-python/packages/source-python/commands/auth.py", line 44, in call
return self.callback(*args)
File "../addons/source-python/packages/source-python/menus/queue.py", line 267, in _menuselect_callback
_radio_queues[index]._select(choice)
File "../addons/source-python/packages/source-python/menus/queue.py", line 126, in _select
next_menu = active_menu._select(self._index, choice)
File "../addons/source-python/packages/source-python/menus/radio.py", line 316, in _select
return super()._select(player_index, choice_index)
File "../addons/source-python/packages/source-python/menus/radio.py", line 113, in _select
self._player_pages[player_index].options[choice_index])
File "../addons/source-python/packages/source-python/menus/base.py", line 122, in _select
return self.select_callback(self, player_index, choice_index)
File "../addons/source-python/plugins/wcs/core/menus/select.py", line 571, in wcsadmin_management_races_add_menu_select
data['races'].append(option.value)
KeyError: 'races'

Hmm, not sure why this exception happens. Did you perhaps modify the file while WCS was loaded?

> I got rid of the error by deleting a file items.json cfg/source-python/wcs/...
races/items/ working in the game
is this normal’’?
But the error remains [SP] Avertissement rencontré:
File '../addons/source-python/plugins/wcs/core/modules/races/manager.py', line 199: UserWarning
Unable to find the default race "". Using "undead_scourge" as temporary default
race.

That warning is normal. It means it cannot find the default race (which by default is not set to anything). To remove it, modify `wcs_default_race` in the `config.cfg` file by setting it to a valid races.

**Comment by herlak** [comment]
thank you very much You have already deleted files races.json & items.json They are rewritten by default
This solved me some problems I was having But I need help how to config  wcs_default_race  As an example 
thank you very much Your whole work is good

**Comment by ThaPwned** [comment]
> 
> 
> thank you very much You have already deleted files races.json & items.json They are rewritten by default
> This solved me some problems I was having But I need help how to config wcs_default_race As an example
> thank you very much Your whole work is good

You open the `../cfg/source-python/wcs/config.cfg` file and go to line 73. It'd looks like this: `wcs_default_race ""`. You then insert the race you want to be default between the double quotes, like so (for Undead Scourge): `wcs_default_race "undead_scourge"` Notice how I wrote `undead_scourge` instead of `Undead Scourge`? That's because it must be the race's shortname, and not the translated name.

**Comment by herlak** [comment]
thank you very much problème résolu
